In [2]:
import numpy as np

## Array Creation

In [3]:
# Creating a new 1-dimensinal array (like standard range() function)
a = np.arange(10, 25)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
# Type is ndarray (n-dimensional array)
type(a)

numpy.ndarray

In [5]:
# Change dimensionality with the reshape method
a.reshape(3, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
#Does not modify in place. 'a' is still 1-dimensional.
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
# Using '-1' will use whatever is required.
a = a.reshape(3, -1)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
# Array attributes
{
    'object type': type(a),
    'dimensions': a.ndim,
    'shape': a.shape,
    'data type': a.dtype.name,
    'bytes per item': a.itemsize,
    'number of items in array': a.size
}

{'bytes per item': 8,
 'data type': 'int64',
 'dimensions': 2,
 'number of items in array': 15,
 'object type': numpy.ndarray,
 'shape': (3, 5)}

In [9]:
# Creating arrays from list or tuples.
# Data type is inferred, but can be supplied explicitly.
a = np.array( [2, 3, 4] )
b = np.array( [1.2, 3.5, 5.1] )
c = np.array( [1, 2, 3, 4], dtype = complex)
[a, a.dtype.name, b, b.dtype.name, c, c.dtype.name]

[array([2, 3, 4]),
 'int64',
 array([ 1.2,  3.5,  5.1]),
 'float64',
 array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j]),
 'complex128']

In [10]:
# Sequences of sequences result in n-dimensional arrays
# 2D
a = np.array( [ (1, 2, 3), (4, 5, 6) ] )
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 3D
b = np.array( [ ( (1,2), (3,4) ), ( (5,6), (7,8) ) ] )
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
# Creating placeholder arrays
a = np.ones( (2, 3) )
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
b = np.zeros( (2, 3) )
b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
c = np.empty( (2, 3) )
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
# Creating sequences
a = np.arange(10, 30, 5)
b = np.arange(0, 2, 0.3)
c = np.linspace( 0, 2, 5)

{
    '10 to 30 by 5': a,
    '0 to 2 by 0.3': b, 
    '0 to 2: 5 steps': c
}

{'0 to 2 by 0.3': array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8]),
 '0 to 2: 5 steps': array([ 0. ,  0.5,  1. ,  1.5,  2. ]),
 '10 to 30 by 5': array([10, 15, 20, 25])}

## Printing

In [16]:
# Last axis printed left to right
# Second-to-last printed top to bottom
# Remaining printed top to bottom separated by empty line
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
# Large arrays skip printing of the central parts
np.arange(1200).reshape(2, 3, -1)

array([[[   0,    1,    2, ...,  197,  198,  199],
        [ 200,  201,  202, ...,  397,  398,  399],
        [ 400,  401,  402, ...,  597,  598,  599]],

       [[ 600,  601,  602, ...,  797,  798,  799],
        [ 800,  801,  802, ...,  997,  998,  999],
        [1000, 1001, 1002, ..., 1197, 1198, 1199]]])

In [18]:
np.arange(1200).reshape(2, -1, 3)

array([[[   0,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8],
        ..., 
        [ 591,  592,  593],
        [ 594,  595,  596],
        [ 597,  598,  599]],

       [[ 600,  601,  602],
        [ 603,  604,  605],
        [ 606,  607,  608],
        ..., 
        [1191, 1192, 1193],
        [1194, 1195, 1196],
        [1197, 1198, 1199]]])

## Basic Operations

In [19]:
# Arithmatic applies elementwise
a = np.array( [20, 30, 40, 50] )
b = np.arange(4)
c = a-b
d = b**2
e = np.sin(a)
f = a<35

{
    'a': a,
    'b': b,
    'c': c, 
    'd': d,
    'e': e,
    'f': f
}

{'a': array([20, 30, 40, 50]),
 'b': array([0, 1, 2, 3]),
 'c': array([20, 29, 38, 47]),
 'd': array([0, 1, 4, 9]),
 'e': array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485]),
 'f': array([ True,  True, False, False], dtype=bool)}

In [20]:
# Multiplication operator '*' operates elementwise.
# Matrix multiplication is done by the 'dot()' function.
A = np.array( [[1, 1],
               [0, 1]] )
B = np.array( [[2, 0],
               [3, 4]] )

In [21]:
A*B

array([[2, 0],
       [0, 4]])

In [22]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [23]:
# In place modifications
a = np.ones( (2, 3), dtype = int)
b = np.random.random( (2, 3) )
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [24]:
b += a
b

array([[ 3.42372244,  3.82674699,  3.86263931],
       [ 3.48931677,  3.32279578,  3.20180046]])

In [25]:
# b is converted to a's integer type, because no new array is being created.
a += b
a

array([[6, 6, 6],
       [6, 6, 6]])

In [26]:
# Array operations create new arrays of the more general data type (upcasting)
a = np.ones(3, dtype=int)
b = np.linspace(0, np.pi, 3)
c = a + b
d = np.exp(c*1j)
{
    'a': a,
    'b': b,
    'c': c,
    'd': d,
    'a-dtype': a.dtype.name,
    'b-dtype': b.dtype.name,
    'c-dtype': c.dtype.name,
    'd-dtype': d.dtype.name
}

{'a': array([1, 1, 1]),
 'a-dtype': 'int64',
 'b': array([ 0.        ,  1.57079633,  3.14159265]),
 'b-dtype': 'float64',
 'c': array([ 1.        ,  2.57079633,  4.14159265]),
 'c-dtype': 'float64',
 'd': array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
        -0.54030231-0.84147098j]),
 'd-dtype': 'complex128'}

In [27]:
# Unary operations implemented as ndarray methods.
# Using the full array without regard to its dimensions.
a = np.random.random( (2, 3) )
{
    'a': a,
    'sum': a.sum(),
    'min': a.min(),
    'max': a.max(), 
    'std': a.std(),
    'mean': a.mean()
}

{'a': array([[ 0.64633279,  0.93984752,  0.62987901],
        [ 0.87741206,  0.65502296,  0.11173569]]),
 'max': 0.93984751792155119,
 'mean': 0.64337167009960872,
 'min': 0.11173568993922045,
 'std': 0.26634445710200744,
 'sum': 3.8602300205976525}

In [28]:
# Specifying the axis parameter
b = np.arange(12).reshape(3, 4)
{
    'b': b,
    'colsum': b.sum(axis = 0),
    'rowsum': b.sum(axis = 1),
    'colmax': b.max(axis = 0),
    'cumsum': b.cumsum(axis = 1)
}

{'b': array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 'colmax': array([ 8,  9, 10, 11]),
 'colsum': array([12, 15, 18, 21]),
 'cumsum': array([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]]),
 'rowsum': array([ 6, 22, 38])}

In [29]:
# 3D array
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
c.max(axis = 0)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
c.sum(axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [32]:
c.min(axis = 2)

array([[ 0,  4,  8],
       [12, 16, 20]])

## Universal Functions

In [33]:
# Universal functions (ufunc) like sin, con, and exp operate elementwise.
B = np.arange(3)
C = np.array( [2., -1., 4.] )
{
    'B': B,
    'C': C,
    'exp': np.exp(B),
    'sqrt': np.sqrt(B),
    'add': np.add(B, C)
}

{'B': array([0, 1, 2]),
 'C': array([ 2., -1.,  4.]),
 'add': array([ 2.,  0.,  6.]),
 'exp': array([ 1.        ,  2.71828183,  7.3890561 ]),
 'sqrt': array([ 0.        ,  1.        ,  1.41421356])}

## Indexing and Slicing

One-Dimensional Arrays

In [34]:
# One-dimensional arrays can be indexed, sliced and iterated over normally.
a = np.arange(10)**3
{
    '1. a': a,
    '2. a[2]': a[2],
    '3. a[2:5]': a[2:5],
}

{'1. a': array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]),
 '2. a[2]': 8,
 '3. a[2:5]': array([ 8, 27, 64])}

In [35]:
# Reversed
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [36]:
# Set every second element
a[::2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125, -1000,   343, -1000,   729])

In [37]:
for i in a:
    print(i**2)

1000000
1
1000000
729
1000000
15625
1000000
117649
1000000
531441


Multi-Dimensional Arrays

In [38]:
def f(x, y):
    return 10*x + y

In [39]:
b = np.fromfunction(f, (5, 4), dtype = int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [40]:
b[2, 3]

23

In [41]:
b[..., 3]

array([ 3, 13, 23, 33, 43])

In [42]:
b[ : , 3]

array([ 3, 13, 23, 33, 43])

In [43]:
b[1:5, 1]

array([11, 21, 31, 41])

In [44]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [45]:
b[-1, -1]

43

In [46]:
b[-1]

array([40, 41, 42, 43])

In [47]:
b[-1][::-1]

array([43, 42, 41, 40])

In [48]:
c = np.array( [ [[0, 1, 2], 
                 [10, 12, 13]],
               
                [[100, 101, 102], 
                 [110, 112, 113]]
              ] )
c.shape

(2, 2, 3)

In [49]:
c[1, ...] # same as c[1, :, :]

array([[100, 101, 102],
       [110, 112, 113]])

In [50]:
c[..., 2] # same as c[: ,: , 2]

array([[  2,  13],
       [102, 113]])

Iterating

In [51]:
# Iteration with respect to first axis (axis = 0)
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [52]:
# Iterate over all elements of an array by 'flattening' it
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape Manipulation

Changing shape of single array

In [53]:
a = np.floor(10*np.random.random( (3, 4) ))
a

array([[ 9.,  8.,  8.,  2.],
       [ 5.,  6.,  1.,  0.],
       [ 0.,  8.,  2.,  8.]])

In [54]:
a.shape

(3, 4)

In [55]:
# Flatten array
a.ravel()

array([ 9.,  8.,  8.,  2.,  5.,  6.,  1.,  0.,  0.,  8.,  2.,  8.])

In [56]:
# Directly modify shape attribute
a.shape = (6, 2)
a.shape

(6, 2)

In [57]:
# reshape() returns new array
a.reshape(2, 6)
a.shape

(6, 2)

In [58]:
# resize() modifies in place
a.resize(2, 6)
a.shape

(2, 6)

In [59]:
a

array([[ 9.,  8.,  8.,  2.,  5.,  6.],
       [ 1.,  0.,  0.,  8.,  2.,  8.]])

In [60]:
# Transpose
a.transpose()

array([[ 9.,  1.],
       [ 8.,  0.],
       [ 8.,  0.],
       [ 2.,  8.],
       [ 5.,  2.],
       [ 6.,  8.]])

Stacking arrays

In [61]:
a = np.floor( 10*np.random.random( (2, 2) ) )
a

array([[ 5.,  1.],
       [ 8.,  3.]])

In [62]:
b = np.floor( 10*np.random.random( (2, 2) ) )
b

array([[ 7.,  1.],
       [ 9.,  7.]])

In [63]:
np.vstack( (a, b) )

array([[ 5.,  1.],
       [ 8.,  3.],
       [ 7.,  1.],
       [ 9.,  7.]])

In [64]:
np.hstack( (a, b) )

array([[ 5.,  1.,  7.,  1.],
       [ 8.,  3.,  9.,  7.]])

In [65]:
c = np.arange(2)
c

array([0, 1])

In [66]:
np.vstack( (c, c) )

array([[0, 1],
       [0, 1]])

In [86]:
def my_function(x, y):
    return x*10 + y

In [87]:
X = np.fromfunction(my_function, (5, 2))
X

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.],
       [ 30.,  31.],
       [ 40.,  41.]])

In [72]:
sum = X[:, 0] + X[:, 1]

In [73]:
np.column_stack((X, sum))

array([[ 0.32003888,  0.33584362,  0.6558825 ],
       [ 0.42922061,  0.960593  ,  1.38981361],
       [ 0.75407587,  0.33559957,  1.08967544],
       [ 0.96181487,  0.93180133,  1.8936162 ],
       [ 0.94511555,  0.59501429,  1.54012984]])

In [90]:
results_x = [np.nan]
results_y = [np.nan]
for i in range(1, X.shape[0]):
    results_x.append(X[i, 0] + X[i-1, 0])
    results_y.append(X[i, 1] + X[i-1, 1])
np.column_stack((X, results_x, results_y))

array([[  0.,   1.,  nan,  nan],
       [ 10.,  11.,  10.,  12.],
       [ 20.,  21.,  30.,  32.],
       [ 30.,  31.,  50.,  52.],
       [ 40.,  41.,  70.,  72.]])

In [93]:
x = np.arange(10)
np.hstack((x, x))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
X

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.],
       [ 30.,  31.],
       [ 40.,  41.]])

In [122]:
percentiles = np.percentile(X, (20, 40, 60, 80), axis = 0)
percentiles

array([[  8.,   9.],
       [ 16.,  17.],
       [ 24.,  25.],
       [ 32.,  33.]])

In [116]:
percentiles.ravel('F')
    

array([  8.,   9.,  16.,  17.,  24.,  25.,  32.,  33.])