In [ ]:
import numpy as np

## Array Creation

In [2]:
# Creating a new 1-dimensinal array (like standard range() function)
a = np.arange(10, 25)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
# Type is ndarray (n-dimensional array)
type(a)

numpy.ndarray

In [4]:
# Change dimensionality with the reshape method
a.reshape(3, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
#Does not modify in place. 'a' is still 1-dimensional.
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
# Using '-1' will use whatever is required.
a = a.reshape(3, -1)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
# Array attributes
{
    'object type': type(a),
    'dimensions': a.ndim,
    'shape': a.shape,
    'data type': a.dtype.name,
    'bytes per item': a.itemsize,
    'number of items in array': a.size
}

{'bytes per item': 8,
 'data type': 'int64',
 'dimensions': 2,
 'number of items in array': 15,
 'object type': numpy.ndarray,
 'shape': (3, 5)}

In [8]:
# Creating arrays from list or tuples.
# Data type is inferred, but can be supplied explicitly.
a = np.array( [2, 3, 4] )
b = np.array( [1.2, 3.5, 5.1] )
c = np.array( [1, 2, 3, 4], dtype = complex)
[a, a.dtype.name, b, b.dtype.name, c, c.dtype.name]

[array([2, 3, 4]),
 'int64',
 array([ 1.2,  3.5,  5.1]),
 'float64',
 array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j]),
 'complex128']

In [9]:
# Sequences of sequences result in n-dimensional arrays
# 2D
a = np.array( [ (1, 2, 3), (4, 5, 6) ] )
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 3D
b = np.array( [ ( (1,2), (3,4) ), ( (5,6), (7,8) ) ] )
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
# Creating placeholder arrays
a = np.ones( (2, 3) )
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
b = np.zeros( (2, 3) )
b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
c = np.empty( (2, 3) )
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
# Creating sequences
a = np.arange(10, 30, 5)
b = np.arange(0, 2, 0.3)
c = np.linspace( 0, 2, 5)

{
    '10 to 30 by 5': a,
    '0 to 2 by 0.3': b, 
    '0 to 2: 5 steps': c
}

{'0 to 2 by 0.3': array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8]),
 '0 to 2: 5 steps': array([ 0. ,  0.5,  1. ,  1.5,  2. ]),
 '10 to 30 by 5': array([10, 15, 20, 25])}

## Printing

In [15]:
# Last axis printed left to right
# Second-to-last printed top to bottom
# Remaining printed top to bottom separated by empty line
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
# Large arrays skip printing of the central parts
np.arange(1200).reshape(2, 3, -1)

array([[[   0,    1,    2, ...,  197,  198,  199],
        [ 200,  201,  202, ...,  397,  398,  399],
        [ 400,  401,  402, ...,  597,  598,  599]],

       [[ 600,  601,  602, ...,  797,  798,  799],
        [ 800,  801,  802, ...,  997,  998,  999],
        [1000, 1001, 1002, ..., 1197, 1198, 1199]]])

In [17]:
np.arange(1200).reshape(2, -1, 3)

array([[[   0,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8],
        ..., 
        [ 591,  592,  593],
        [ 594,  595,  596],
        [ 597,  598,  599]],

       [[ 600,  601,  602],
        [ 603,  604,  605],
        [ 606,  607,  608],
        ..., 
        [1191, 1192, 1193],
        [1194, 1195, 1196],
        [1197, 1198, 1199]]])

## Basic Operations

In [18]:
# Arithmatic applies elementwise
a = np.array( [20, 30, 40, 50] )
b = np.arange(4)
c = a-b
d = b**2
e = np.sin(a)
f = a<35

{
    'a': a,
    'b': b,
    'c': c, 
    'd': d,
    'e': e,
    'f': f
}

{'a': array([20, 30, 40, 50]),
 'b': array([0, 1, 2, 3]),
 'c': array([20, 29, 38, 47]),
 'd': array([0, 1, 4, 9]),
 'e': array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485]),
 'f': array([ True,  True, False, False], dtype=bool)}

In [19]:
# Multiplication operator '*' operates elementwise.
# Matrix multiplication is done by the 'dot()' function.
A = np.array( [[1, 1],
               [0, 1]] )
B = np.array( [[2, 0],
               [3, 4]] )

In [20]:
A*B

array([[2, 0],
       [0, 4]])

In [21]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [22]:
# In place modifications
a = np.ones( (2, 3), dtype = int)
b = np.random.random( (2, 3) )
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [23]:
b += a
b

array([[ 3.34719226,  3.10133904,  3.23072802],
       [ 3.01728202,  3.63103169,  3.2445957 ]])

In [24]:
# b is converted to a's integer type, because no new array is being created.
a += b
a

array([[6, 6, 6],
       [6, 6, 6]])

In [25]:
# Array operations create new arrays of the more general data type (upcasting)
a = np.ones(3, dtype=int)
b = np.linspace(0, np.pi, 3)
c = a + b
d = np.exp(c*1j)
{
    'a': a,
    'b': b,
    'c': c,
    'd': d,
    'a-dtype': a.dtype.name,
    'b-dtype': b.dtype.name,
    'c-dtype': c.dtype.name,
    'd-dtype': d.dtype.name
}

{'a': array([1, 1, 1]),
 'a-dtype': 'int64',
 'b': array([ 0.        ,  1.57079633,  3.14159265]),
 'b-dtype': 'float64',
 'c': array([ 1.        ,  2.57079633,  4.14159265]),
 'c-dtype': 'float64',
 'd': array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
        -0.54030231-0.84147098j]),
 'd-dtype': 'complex128'}

In [26]:
# Unary operations implemented as ndarray methods.
# Using the full array without regard to its dimensions.
a = np.random.random( (2, 3) )
{
    'a': a,
    'sum': a.sum(),
    'min': a.min(),
    'max': a.max(), 
    'std': a.std(),
    'mean': a.mean()
}

{'a': array([[ 0.44039799,  0.74969275,  0.50375616],
        [ 0.7534239 ,  0.28734815,  0.71697109]]),
 'max': 0.7534239025678775,
 'mean': 0.575265007380792,
 'min': 0.28734815317944329,
 'std': 0.17722160544492313,
 'sum': 3.4515900442847522}

In [27]:
# Specifying the axis parameter
b = np.arange(12).reshape(3, 4)
{
    'b': b,
    'colsum': b.sum(axis = 0),
    'rowsum': b.sum(axis = 1),
    'colmax': b.max(axis = 0),
    'cumsum': b.cumsum(axis = 1)
}

{'b': array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 'colmax': array([ 8,  9, 10, 11]),
 'colsum': array([12, 15, 18, 21]),
 'cumsum': array([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]]),
 'rowsum': array([ 6, 22, 38])}

In [28]:
# 3D array
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
c.max(axis = 0)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
c.sum(axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [31]:
c.min(axis = 2)

array([[ 0,  4,  8],
       [12, 16, 20]])

## Universal Functions

In [38]:
# Universal functions (ufunc) like sin, con, and exp operate elementwise.
B = np.arange(3)
C = np.array( [2., -1., 4.] )
{
    'B': B,
    'C': C,
    'exp': np.exp(B),
    'sqrt': np.sqrt(B),
    'add': np.add(B, C)
}

{'B': array([0, 1, 2]),
 'C': array([ 2., -1.,  4.]),
 'add': array([ 2.,  0.,  6.]),
 'exp': array([ 1.        ,  2.71828183,  7.3890561 ]),
 'sqrt': array([ 0.        ,  1.        ,  1.41421356])}

## Indexing and Slicing

One-Dimensional Arrays

In [50]:
# One-dimensional arrays can be indexed, sliced and iterated over normally.
a = np.arange(10)**3
{
    '1. a': a,
    '2. a[2]': a[2],
    '3. a[2:5]': a[2:5],
}

{'1. a': array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]),
 '2. a[2]': 8,
 '3. a[2:5]': array([ 8, 27, 64])}

In [51]:
# Reversed
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [ ]:
# Set every second element
a[::2] = -1000
a

In [54]:
for i in a:
    print(i**2)

1000000
1
1000000
729
1000000
15625
1000000
117649
1000000
531441


Multi-Dimensional Arrays